import { Link } from "react-router-dom"
import Meta from "../components/Meta"
import { serviceEntries, projectEntries } from "../data/content"

export default function HomeRestored() {
  return <>
    <Meta title="DM Digital Solutions | Digital systems for growing businesses" description="Digital solutions built around the way your business works: websites, commerce, booking, software, automation, and AI." />
    <section className="hero home-landing-hero"><div className="container home-landing-grid"><div className="home-landing-copy"><p className="eyebrow">Digital solutions for growing businesses</p><h1>Digital systems built around the way your business works.</h1><p className="hero-statement">Build better. Sell smarter. Operate simpler.</p><p className="hero-copy">Websites, e-commerce, booking systems, custom software, automation, and AI solutions designed around the way your business actually operates.</p><div className="hero-actions"><Link className="btn btn-primary" to="/contact">Start a project</Link><Link className="btn btn-secondary" to="/services">Explore services</Link></div><div className="hero-tags"><span>Websites</span><span>E-commerce</span><span>Business systems</span><span>Automation</span></div></div><div className="hero-hub home-landing-hub" aria-label="DM Digital business systems preview"><div className="hub-toolbar"><strong>DM Business Hub</strong><span>Connected workflows</span></div><div className="hub-grid">{[["Revenue", "PHP 89,240"], ["Orders", "243"], ["Appointments", "56"], ["Customers", "1,847"]].map(([label, value]) => <div className="metric-tile" key={label}><span>{label}</span><strong>{value}</strong><small>Live overview</small></div>)}</div><div className="hub-activity">{["Website inquiry", "New order", "Appointment", "Automation"].map((item) => <div className="activity-card" key={item}><small>Recent activity</small><strong>{item}</strong><span>Ready for the next step</span></div>)}</div></div></div></section>
    <section className="section section-muted"><div className="container"><div className="section-title"><p className="eyebrow">What we build</p><h2>Start with the business problem.</h2><p className="lead">Choose a focused digital solution now, with room to grow into a stronger system later.</p></div><div className="home-card-grid">{serviceEntries.slice(0, 3).map((service, index) => <article className="detail-card" key={service.slug}><div className="detail-top"><span>0{index + 1}</span><p className="eyebrow">{service.level}</p></div><h3>{service.title}</h3><p>{service.summary}</p><Link className="text-link" to={`/services/${service.slug}`}>Explore service →</Link></article>)}</div><Link className="button" to="/services">View all services</Link></div></section>
    <section className="section"><div className="container"><div className="section-title"><p className="eyebrow">Selected work</p><h2>Systems that make complex work easier to see.</h2></div><div className="home-card-grid">{projectEntries.map((project) => <article className="detail-card" key={project.slug}><p className="eyebrow">{project.category}</p><h3>{project.title}</h3><p>{project.summary}</p><div className="tag-row">{project.features.slice(0, 2).map((feature) => <span key={feature}>{feature}</span>)}</div><Link className="text-link" to={`/projects/${project.slug}`}>View project →</Link></article>)}</div></div></section>
    <section className="section section-muted"><div className="container home-principles"><div className="section-title"><p className="eyebrow">Why DM Digital</p><h2>Built for your business, not a template.</h2><p className="lead">Minimal on the surface. Thoughtful underneath.</p></div><div className="principles"><article><span>01</span><h3>Business-first</h3><p>We start with the problem, not the technology.</p></article><article><span>02</span><h3>Custom-built</h3><p>Solutions are shaped around your actual workflow.</p></article><article><span>03</span><h3>Long-term support</h3><p>Useful systems can improve as the business evolves.</p></article></div></div></section>
    <section className="cta-band home-final-cta"><div className="container"><p className="eyebrow">Ready when you are</p><h2>Have a business process you would like to improve?</h2><p>Tell us what you are trying to improve, and we will help identify the right digital solution.</p><Link className="button button-light" to="/contact">Start a project</Link></div></section>
  </>
}
